### ISSUE TITLE
TareaDescargarCSV

### ISSUE THREAD

**Issue by MarcEslava** [PMFARMA/IESALINES_API#7]
Especificaciones Técnicas:

EndPoint: /jurado/csv
controller: JuradoController
method-controller:descargarCSV
REST-Method: GET

Descripción:

instalar laravel-excel de https://laravel-excel.com/
seguir los pasos de configuración

https://www.youtube.com/watch?v=fHTMdKfQfok

importar Exports del nuevo paquete en el controlador JuradoController
Hacer una query con los datos correspondientes y retornar el CSV.

**Comment by eloy411** [comment]
queda ver si ponemos cabecera
